postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  dbname: "tfmv"
  sslmode: "disable"
  secret_name: "projects/858338514445/secrets/postgres-pwd/versions/latest"

gcs:
  bucket_name: "tfmv-gcs-to-pg"
  project_id: "tfmv-371720"
  dataset: "tfmv"
  files:
    - name: "regions.parquet"
      table: "regions"
    - name: "supplier.avro"
      table: "supplier"
  concurrent_jobs: 1

bq:
  project_id: "tfmv-371720"
  dataset: "tpch"
  tables:
    - name: "nation"
      table: "nation"
